/**
 * Test helpers index - re-exports all helper modules
 */

// Service availability detection
export {
  TEST_CONFIG,
  type ServiceStatus,
  type AllServicesStatus,
  withTimeout,
  checkN8nConnectivity,
  checkPostgresConnectivity,
  checkS3Connectivity,
  checkQdrantConnectivity,
  checkGraphitiConnectivity,
  checkRedisConnectivity,
  checkAllServices,
  waitForServices,
  shouldSkipIfServiceUnavailable,
  logServiceStatus,
  createTestS3Client,
  createTestDbClient,
} from './service-availability';

// Test fixtures
export {
  generateTestId,
  type TestProject,
  createTestProject,
  createTestInputFile,
  createTestInputFiles,
  createTestTechItem,
  createTestTechStack,
  createGovernancePayload,
  createApproveAllResponse,
  createSkipAllResponse,
  createMixedDecisionsResponse,
  createWithAlternativesResponse,
  createProjectState,
  createProjectStateAtPhase,
  createStartProjectRequest,
  createPresignedUrlRequest,
  type DecisionLogEntry,
  createDecisionLogEntry,
  createCompleteDecisionLog,
  createVisionDocumentContent,
  createArchitectureDocumentContent,
  createDecisionLogContent,
} from './test-fixtures';

// S3 helpers
export {
  createS3Client,
  ensureBucketExists,
  uploadContent,
  uploadTestFile,
  uploadTestArtifact,
  generateUploadUrl,
  uploadWithPresignedUrl,
  downloadContent,
  generateDownloadUrl,
  fileExists,
  getFileMetadata,
  verifyFileContent,
  listFiles,
  listProjectInputFiles,
  listProjectArtifacts,
  listAllProjectFiles,
  deleteFile,
  deleteByPrefix,
  cleanupProject as cleanupS3Project,
  cleanupByTestPrefix as cleanupS3ByTestPrefix,
  setupProjectWithFiles,
  setupProjectWithArtifacts,
  setupCompleteProjectStructure,
} from './s3-helpers';

// Database helpers
export {
  createDbClient,
  type ProjectStateRow,
  insertProject,
  getProjectState,
  updateProjectPhase,
  updateProjectIteration,
  updateProjectTechStandards,
  updateProjectArtifacts,
  completeProject,
  deleteProject,
  insertDecisionLogEntry,
  getDecisionLogEntries,
  getDecisionLogEntriesByPhase,
  countDecisionLogEntriesByType,
  type ChatMessageRow,
  insertChatMessage,
  getChatMessages,
  cleanupProject as cleanupDbProject,
  cleanupByTestPrefix as cleanupDbByTestPrefix,
  resetTestDatabase,
  setupProjectAtPhase,
  setupProjectWithDecisionLog,
  assertProjectPhase,
  assertDecisionLogHasEntries,
} from './db-helpers';

// Wait/polling helpers
export {
  type WaitOptions,
  type WaitResult,
  waitForCondition,
  waitForValue,
  sleep,
  retryWithBackoff,
  waitForProjectPhase,
  waitForProjectCompletion,
  waitForProjectStatus,
  waitForScoreThreshold,
  waitForFile,
  waitForArtifact,
  waitForVisionFinal,
  waitForArchitectureFinal,
  waitForDecisionLog,
  waitForEndpoint,
  waitForWebhookCall,
  waitForAll,
  waitForAny,
  createTimeout,
  withTimeout as withTimeoutPromise,
  createDeferred,
} from './wait-helpers';
